# Generated by Django 4.1.3 on 2022-11-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tode',
            new_name='Todo',
        ),
    ]
