# Generated by Django 4.1.3 on 2022-12-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_tode_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='estimated_end',
            field=models.DateField(),
        ),
    ]
