# Generated by Django 4.1.3 on 2022-11-09 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('movil', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('compania', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('notes', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
